apps/blog/api/blog/urls.py
from django.conf.urls import url

# from .views import *

urlpatterns = [

    # url(r'^get-site-view$', GetSiteView.as_view(), name="get-site-view"),
]

apps/blog/urls.py
from django.conf.urls import url, include
# para poder importar las imagenes
from .views import (Blog, Detalle_blog, buscador_blog,
					buscador_categoria, AcercaDe, contador_visitas, tags)
# from views import Users
from django.conf import settings

# from django.views.static.
urlpatterns = [
    # url(r'^users', Users.as_view(), name='inicio'),
    # cuidado con esto tiene GRUD de Users
    # url(r'^$', UserVer.as_view(), name='p_inicio'),
    url(r'api/', include(('apps.blog.api.blog.urls', 'api_blog'), namespace='api_blog')),
    url(r'^$', Blog.as_view(),
        name='p_inicio'),
    url(r'^buscador/$', buscador_blog, name='p_buscador_blog'),
    url(r'^contador-visitas-ajax/$', contador_visitas, name='p_contador_visitas'),
    url(r'^acerca/$', AcercaDe.as_view(), name='p_acerca_de'),
    url(r'^tags/(?P<slug>[^/]+)/$', tags, name='p_tag_blog'),
    url(r'^buscador/categorias/(?P<slug>[^/]+)/$',
        buscador_categoria, name='p_buscador_categoria'),
    url(r'^(?P<slug>[^/]+)/$', Detalle_blog.as_view(), name='p_detalle_blog'),
    
]

yachaycode/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.views import (change_password, 
                                        registro_usuario_modals, 
                                        Completar_registro_perfil,
                                        Registrarse, Index_principal,
                                        LogOut, userlogin,
                                        activate)
from apps.users import views as core_views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', Index_principal.as_view(), name="index_principal"),
    path(r'oauth/', include('social_django.urls', namespace='social')),
    path(r'usuarios/', include(('apps.users.urls', 'app_users'), 
        namespace='app_users')),
    path(r'blog/', include(('apps.blog.urls', 'app_blog'), 
        namespace='app_blog')),
    path(r'settings/', core_views.settings, name='settings'),
    path(r'settings/password/', core_views.password, name='password'),
    path(r'iniciar/', userlogin, name="iniciar_sesion"),
    path(r'salir/', LogOut, name='cerrar_sesion'),
        # para recuperacion de contraseña
    path('', include('django.contrib.auth.urls')),
    path(r'registrarse/', Registrarse.as_view(), 
        name="registrarse_usuario"),
    path('martor/', include('martor.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

apps/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from apps.users.models import User
from martor.models import MartorField
# Create your models here.
class Category(models.Model):

    name = models.CharField(max_length=180, unique=True)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = ('Categories')

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=350, unique=True)
    slug = models.SlugField(editable=False, null=True, max_length=250)
    summary = models.TextField(null=True, max_length=1800)
    content = MartorField()
    categories = models.ManyToManyField(Category)
    cover_image = models.ImageField(upload_to='cover-images-blog', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    number_views = models.PositiveIntegerField(default=0, blank=True, null=True)
    keywords = models.CharField(max_length=800, null=True, blank=True) 
    status = models.BooleanField(default=True)
    is_main_article = models.BooleanField(default=False)
    related_posts = models.ManyToManyField("self",
                                     verbose_name=("Related posts"), blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title or u''

# De momento no se esta usando
class VisitorCounter(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    counter = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.blog, self.counter) or u''

apps/blog/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.views.generic import ListView, TemplateView, DetailView
from .models import Blog as Blogs, Category
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# para paginador
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.sites.shortcuts import get_current_site
# Create your views here.
class Blog(ListView):
    """docstring for ver_todas_tortas"""
    context_object_name = 'blogs'
    template_name = 'blog/blog.html'
    paginate_by = 12
    model = Blogs
    def get_context_data(self, *args, **kwargs):
        context_data = super(Blog, self).get_context_data(*args, **kwargs)
        # realizamos consulta de todos los categories de blogs
        blogs = Blogs.objects.filter(status=True).order_by('-created_at')
        list_blogs = []
        for blog in blogs:
           dict_blog = {}
           dict_blog['title'] = blog.title
           dict_blog['slug'] = blog.slug
           dict_blog['summary'] = blog.summary[0:250] + '...' if len(blog.summary)>250 else blog.summary
           dict_blog['content'] = blog.content
           dict_blog['categories'] = blog.categories
           dict_blog['cover_image'] = blog.cover_image
           dict_blog['created_at'] = blog.created_at
           dict_blog['author'] = blog.author
           dict_blog['number_views'] = blog.number_views
           dict_blog['keywords'] = blog.keywords
           dict_blog['status'] = blog.status
           dict_blog['is_main_article'] = blog.is_main_article
           dict_blog['related_posts'] = blog.related_posts
           list_blogs.append(dict_blog)
        context_data['blogs'] = list_blogs
        context_data['categories_blog'] = Category.objects.all()

        return context_data

class Detalle_blog(DetailView):
    """docstring for Detalle_curso"""
    # ordenar los modulos segun el orden de creacion
    context_object_name = 'detalle_blog'
    template_name = "blog/detalle_blog.html"
    model = Blogs
    slug_field = 'slug'

    def get_domain(self):
        current_site = get_current_site(self.request)  
        if current_site.domain in ['localhost', 'example.com']:
            sheme = 'http://'
        else:
            sheme = 'https://'
        return sheme + current_site.domain

    def get_context_data(self, *args, **kwargs):
        context_data = super(Detalle_blog, self).get_context_data(*args, **kwargs)
        # realizamos consulta de todos los categories de blogs
        context_data['domain'] = self.get_domain()
        return context_data


def buscador_blog(request):


    """docstring for Busqueda"""
    # todo tipo de buscador siempre buscara con cualquier parámetro, 
    # siempre en cuando este status = TRUE, inidica que está activo
    consulta = request.GET.get('q', '')
    lista_blogs = None
    list_blogs = []
    if consulta:
        lista_blogs = Blogs.objects.filter(
            Q(title__icontains=consulta) |
            Q(summary__icontains=consulta) |
            Q(keywords__icontains=consulta) |
            Q(categories__name__icontains=consulta), status=True).distinct()
    # else:
        # en caso si alguien entra directamente a /busquedas
        # lista_blogs = Curso.objects.all().order_by('-fecha_creacion')[:2]
    # paginandor
        for blog in lista_blogs:
           dict_blog = {}
           dict_blog['title'] = blog.title
           dict_blog['slug'] = blog.slug
           dict_blog['summary'] = blog.summary[0:250] + '...' if len(blog.summary)>250 else blog.summary
           dict_blog['content'] = blog.content
           dict_blog['categories'] = blog.categories
           dict_blog['cover_image'] = blog.cover_image
           dict_blog['created_at'] = blog.created_at
           dict_blog['author'] = blog.author
           dict_blog['number_views'] = blog.number_views
           dict_blog['keywords'] = blog.keywords
           dict_blog['status'] = blog.status
           dict_blog['is_main_article'] = blog.is_main_article
           dict_blog['related_posts'] = blog.related_posts
           list_blogs.append(dict_blog)
    paginator = Paginator(list_blogs, 12)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blogs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blogs = paginator.page(paginator.num_pages)

    categories = Category.objects.all()

    return render(request, 'blog/buscador_blog.html',
                  {'blogs': blogs, 'categories': categories})


def buscador_categoria(request, slug):
    try:
        consulta = Blogs.objects.filter(
            categories__slug=slug, status=True)
        list_blogs = []
        for blog in consulta:
           dict_blog = {}
           dict_blog['title'] = blog.title
           dict_blog['slug'] = blog.slug
           dict_blog['summary'] = blog.summary[0:250] + '...' if len(blog.summary)>250 else blog.summary
           dict_blog['content'] = blog.content
           dict_blog['categories'] = blog.categories
           dict_blog['cover_image'] = blog.cover_image
           dict_blog['created_at'] = blog.created_at
           dict_blog['author'] = blog.author
           dict_blog['number_views'] = blog.number_views
           dict_blog['keywords'] = blog.keywords
           dict_blog['status'] = blog.status
           dict_blog['is_main_article'] = blog.is_main_article
           dict_blog['related_posts'] = blog.related_posts
           list_blogs.append(dict_blog)
        categories = Category.objects.all()
        return render(request, 'blog/buscador_blog.html',
                      {'blogs': list_blogs, 'categories': categories})
    except Exception as e:
        raise 

class AcercaDe(TemplateView):
    template_name = 'blog/nosotros.html'

@csrf_exempt 
def contador_visitas(request):
    if request.method == 'POST' and request.is_ajax():
        try:
            status = False
            blog = get_object_or_404(Blogs, 
                status=True, pk=request.POST.get('id'))
            blog.number_views +=1
            blog.save()
            status = True
            response = JsonResponse({'status': status})
            return HttpResponse(response.content)            
        except Exception as e:
            print ("Error:", e)
            response = JsonResponse({'status': status, 'error': str(e)})
            return HttpResponse(response.content)            
    else:
        return redirect('/')

def tags(request, slug):
    try:
      consulta = Blogs.objects.filter(categories__slug=slug)
      categories = Category.objects.all()
      return render(request, 'blog/categories.html',{'blogs': consulta, 'slug': slug})
    except Exception as e:
        print ("Error categories:", e)
        # raise e

apps/blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %}YachayCode - Blog{% endblock title %}
{% block head_imports %}
  <!-- Blog Styles -->
  <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}
{% block section %}

  <div class="container-fluid pt-3 base d-flex justify-content-center">
    <div class="row">
      <picture>
        <!-- Image when width < 768px -->
        <source srcset="{% static 'img/bannerazul.jpg' %}" media="(max-width: 768px)">
        <!-- Normal image -->
        <img loading="lazy" src="{% static 'img/banner.jpg' %}" class="img-fluid" alt="img-yachay">
      </picture>
    </div>
  </div>

  <div class="container mb-5">
    <div class="d-flex">
      <div class="d-flex mt-5 mb-5">
        <div class="btn-group">
          <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <p class="color-grey mb-0">
              Categorias
              <i class="fas fa-angle-down pl-0 size14 color-grey ml-1"></i></a>
            </p>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'app_blog:p_inicio' %}">
              Todos
            </a>
            {% for categoria in categories_blog %}
              <a class="dropdown-item" href="{% url 'app_blog:p_buscador_categoria' categoria.slug  %}">
                {{categoria.name}}
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="d-flex col-md-8 mt-5 mb-5 ml-0">
          <div class="col-md-7 container-1">
              <span class="icon1"><i class="fa fa-search color-blue1"></i></span>
              <form  method="GET" action="{% url 'app_blog:p_buscador_blog' %}" > 
              <input class="form-control search pl" type="search" id="q" name="q" placeholder="Buscar artículos ..." />
              </form>
          </div>
      </div>
    </div>
    <div class="row mb-5">
      {% for blog in blogs %}
        <!-- First text -->
        <div class="col-md-4">
          <p class="size12 f-mont c-r">
            <!-- Startup  -->
          </p>

          <!-- Card image -->
          <a href="{% url 'app_blog:p_detalle_blog' blog.slug %}"><img loading="lazy" class="card-img-top" src="{{ blog.cover_image.url }}" alt="Card image cap"></a>

          <!-- Card content -->
          <div class="card-body m-0 p-0">
            <div class="row pt-1">
              <div class="col-md-6 col-6">
                <p class="size12 m-0 c-gray">
                  {{blog.created_at|date:"d M, Y"}}
                </p>
              </div>
              <div class="col-md-12">
                <a href="{% url 'app_blog:p_detalle_blog' blog.slug %}">
                  <p class="f-mont size18 pt-2 m-0 pb-2">
                    {{blog.title}}
                  </p>
                </a>
              </div>
              <div class="col-md-12">
                <p class="size12 c-gray">
                    {{blog.summary}}
                </p>
              </div>
            </div>
          </div>

          <!-- Card footer -->
          <div class="rounded-bottom lighten-3 pt-0">
            <div class="row pd-gblog mb-1">
              <div class="col-md-8">
                <div class="row justify-content-center">
                  <div class="col-md-2 ">
                    <div class="avatar-blog ">
                      <img src="{{ blog.author.userprofile.photo.url }}" class="rounded-circle img-fluid">
                    </div>
                  </div>
                  <div class="col-md-10  pd-lblog cy-blog">
                    <p class="text-avatar mpg">
                      {% if blog.author.userprofile.first_name and blog.author.userprofile.last_name %}
                        Posteado por <b>{{ blog.author.userprofile.first_name }} {{ blog.author.userprofile.last_name }}</b>
                      {% else %}
                        Posteado por <b>{{ blog.author.userprofile.username }}</b>
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <div>
      <nav aria-label="Page navigation">

        <ul class="pagination pg-blue justify-content-center">

          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previus">
                <!-- <span class="page-link" href="?page={{ contacts.previous_page_number }}">Anterior</span> -->
                <span aria-hidden="true step-links">Anterior</span>
                <span class="sr-only">Anterior</span>
              </a>
            </li>
          {% endif %}

          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">Siguiente</span>
                <span class="sr-only">Siguiente</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
{% endblock section %}

apps/blog/templates/blog/buscador_blog.html
{% extends "base.html" %}
{% block title %}YachayCode | Buscador blog{% endblock title %}
{% load static %}
{% block section %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">

  <div class="container-fluid pt-3 base d-flex justify-content-center">
    <div class="row">
      <picture>
        <!-- Image when width < 768px -->
        <source srcset="{% static 'img/bannerazul.jpg' %}" media="(max-width: 768px)">
        <!-- Normal image -->
        <img loading="lazy" src="{% static 'img/banner.jpg' %}" class="img-fluid" alt="img-yachay">
      </picture>
    </div>
  </div>

  <!-- {% if blogs %}
    <div class="container-fluid">
      <div class="container pt-lg  pt-1 pb-3">
        <div class="row mt-5 mb-3">
          <div class="col-md-12 ">
            <p class="color-blue1 size30 fw700" id="myModalLabel">Lo más reciente de publicaciones</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %} -->

  <div class="container mb-5">
      <div class="d-flex">
        <div class="d-flex mt-5 mb-5">
          <div class="btn-group">
            <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <p class="color-grey mb-0">
                Categorias
                <i class="fas fa-angle-down pl-0 size14 color-grey ml-1"></i></a>
              </p>
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'app_blog:p_inicio' %}">
                Todos
              </a>
              {% for categoria in categories %}
                <a class="dropdown-item" href="{% url 'app_blog:p_buscador_categoria' categoria.slug  %}">
                  {{categoria.name}}
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="d-flex col-md-8 mt-5 mb-5 ml-0">
            <div class="col-md-7 container-1">
                <span class="icon1"><i class="fa fa-search color-blue1"></i></span>
                <form  method="GET" action="{% url 'app_blog:p_buscador_blog' %}" > 
                <input class="form-control search pl" type="search" id="q" name="q" placeholder="Buscar artículos ..." />
                </form>
            </div>
        </div>
      </div>

      <div class="row mb-5">
        {% if blogs %}
          {% for blog in blogs %}
          <!-- First text -->
          <div class="col-md-4">
            <p class="size12 f-mont c-r">
              <!-- Startup  -->
            </p>
  
            <!-- Card image -->
            <a href="{% url 'app_blog:p_detalle_blog' blog.slug %}"><img loading="lazy" class="card-img-top" src="{{ blog.cover_image.url }}" alt="Card image cap"></a>
  
            <!-- Card content -->
            <div class="card-body m-0 p-0">
              <div class="row pt-1">
                <div class="col-md-6 col-6">
                  <p class="size12 m-0 c-gray">
                    {{blog.created_at|date:"d M, Y"}}
                  </p>
                </div>
                <div class="col-md-12">
                  <p class="f-mont size18 pt-2 m-0 pb-2">
                    {{blog.title}}
                  </p>
                </div>
                <div class="col-md-12">
                  <p class="size12 c-gray">
                    {{blog.summary}}
                  </p>
                </div>
                <div class="col-md-12">
                  <span class="color-blue2 size13 pr-2">
                    {% for categoria in blog.categories.all %}
                      {{categoria.name}}
                    {% endfor %}
                  </span>
                  <span class="text-avatar color-lead">{{blog.created_at|date:"d M, Y"}}</span>
                </div>
              </div>
            </div>
  
            <!-- Card footer -->
            <div class="rounded-bottom lighten-3 pt-0">
              <div class="row pd-gblog mb-1">
                <div class="col-md-8">
                  <div class="row justify-content-center">
                    <div class="col-md-2 ">
                      <div class="avatar-blog ">
                        <img src="{{ blog.author.userprofile.photo.url }}" class="rounded-circle img-fluid">
                      </div>
                    </div>
                    <div class="col-md-10  pd-lblog cy-blog">
                      <p class="text-avatar mpg">
                        {% if blog.author.userprofile.first_name and blog.author.userprofile.last_name %}
                          Posteado por <b>{{ blog.author.userprofile.first_name }} {{ blog.author.userprofile.last_name }}</b>
                        {% else %}
                          Posteado por <b>{{ blog.author.userprofile.username }}</b>
                        {% endif %}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        {% else %}
          <p class="f-mont">
            No se encontraron resultados...
          </p>
        {% endif %}
      </div>
  </div>
</div>
{% endblock section %}

apps/blog/templates/blog/detalle_blog.html
{% extends "base.html" %}
{% load static martortags disqus_tags %}

{% block title %} {{detalle_blog.title}} | Blog - YachayCode {% endblock title %}
{% block author %}{{ detalle_blog.author.userprofile.first_name }} {{ detalle_blog.author.userprofile.last_name}}{% endblock author %}
{% block canonical %}{{domain}}/blog/{{ detalle_blog.slug}}{% endblock canonical %}

{% block description %}{% if detalle_blog.seoblog %}{{detalle_blog.seoblog.description}}{% else %}{{detalle_blog.summary}}{% endif %}{% endblock description %}

{% block twitter_title %}{{detalle_blog.title}} | Blog - YachayCode{% endblock twitter_title %}

{% block twitter_description %}{% if detalle_blog.seoblog %}{{detalle_blog.seoblog.description}}{% else %}{{detalle_blog.summary}}{% endif %}{% endblock twitter_description %}

{% block twitter_image %}{{domain}}{{detalle_blog.cover_image.url}}{% endblock twitter_image %}

{% block twitter_creator %}{{detalle_blog.author.userprofile.first_name }} {{detalle_blog.author.userprofile.last_name}}{% endblock twitter_creator %}

{% block og_url %}{{domain}}/blog/{{ detalle_blog.slug}}{% endblock og_url %}

{% block og_title %}{{detalle_blog.title}}{% endblock og_title %}

{% block og_description %}{% if detalle_blog.seoblog %}{{detalle_blog.seoblog.description}}{% else %}{{detalle_blog.summary}}{% endif %}{% endblock og_description %}

{% block og_image %}{{domain}}{{detalle_blog.cover_image.url}}{% endblock og_image %}

{% block keywords %}{{detalle_blog.seoblog.keyword}}{% endblock keywords %}


{% block section %}
<link rel="stylesheet" href="{% static 'blog/css/detailed.css' %}">
  <div class="container-fluid bg-color">
    <!-- detalle blog -->
    <div class="container py-xl-5 py-lg-3">
      <div class="row inner_sec_info pt-md-4 pt-sm-8 justify-content-center">
        <!-- left side -->
        <div class="col-md-10 col-11 single-left card1tg">
          {% if detalle_blog.categories.all %}
                {% for categoria in detalle_blog.categories.all  %}
                  <a href="{% url 'app_blog:p_tag_blog' categoria.slug %}"><span class="size18 c-r f-mont">{{categoria.name}} </span></a>
                {% endfor%}
            {%endif%}
          <h1 class="color_black f-mont f-mont  pb-2">
            {{detalle_blog.title}}
          </h1>
          <span class="size13 f-mont-r">
            {% if detalle_blog.author.userprofile.first_name %}
              Escrito por: <strong>{{ detalle_blog.author.userprofile.first_name }} {{ detalle_blog.author.userprofile.last_name }}</strong>
            {% else %}
              Escrito por: <strong>{{ detalle_blog.author.userprofile.username }}</strong>
            {% endif %}
          </span>
          <ul class="blog_list my-3 pb-3 p-0">
            <li>
              <span class="c-gris size13 f-mont-r">
                {{detalle_blog.created_at|date:"d M, Y"}}
              </span>
            </li>
            <li class="mx-3">
              <span class="c-gris size13 f-mont-r">
                6 min de lectura
              </span>
            </li>
            <li class="mx-3">
              <i class="fas fa-eye mr-1"></i>
              <span class="c-gris size13 f-mont-r">{{detalle_blog.number_views}}</span>
            </li>
            <li>
              <i class="far fa-comments mr-1"></i>
              <a href="#disqus_thread" id="link_to_comments" data-disqus-identifier="102"><script type="text/javascript">
                var disqus_shortname = 'hero';
                  (function () {
                  var s = document.createElement('script'); s.async = true;
                  s.type = 'text/javascript';
                  s.src = '//' + disqus_shortname + '.disqus.com/count.js';
                  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
                  }());
                </script>
                <span class="gris3">comentarios</span>
              </a>
            </li>
          </ul>

          <!-- Contenido -->

          <div class="single-left1">
            <img loading="lazy" src="{{detalle_blog.cover_image.url}}" alt=" " class="img-fluid">
            <p class="pt-5 cont-blog"></p>
            <p class="cont-blog color-blue1">
              {{detalle_blog.content|safe_markdown}}
            </p>
            <input type="hidden" name="id_blog" id="id_blog" value="{{detalle_blog.id}}">
          </div>
          <!--stard relacionados-->
          {% if detalle_blog.related_posts.all %}
            <div class="container-fluid m-0 p-0 ">
              <hr class="mt-5 mb-4">
                <h3 class="blog-title f-mont size30 mb-4">Artículos relacionados</h3>
                <div class="row">
                  
                    {% for post_relacionado in detalle_blog.related_posts.all  %}
                      <div class="col-md-4">
                        <!-- Card -->
                        <div class="">

                          <!-- Card image -->
                          <a href="{% url 'app_blog:p_detalle_blog' post_relacionado.slug %}"> <img class="card-img-top" src="{{post_relacionado.cover_image.url}}" alt="Card image cap"></a>

                          <!-- Card content -->
                          <div class="mt-2">

                           <a href="{% url 'app_blog:p_detalle_blog' post_relacionado.slug %}"><h5 class="card-title f-mont">{{post_relacionado.title}}</h5></a>
                          </div>

                        </div>
                        <!-- Card -->
                      </div>
                    {% endfor %}
               </div>
                <!---->
                {% if detalle_blog.categories.all %}
                   <div class="row mt-4">
                    <div class="col-md-12">
                      <ul class="categoria m-0 p-0">
                        {% for categoria in detalle_blog.categories.all  %}
                          <li>
                            <a href="{% url 'app_blog:p_tag_blog' categoria.slug %}">
                              <span class="card-title f-mont size18">
                                {{categoria.name}}
                              </span>
                            </a>
                          </li>
                        {% endfor%}
                      </ul>
                    </div>
                 </div>
               {%endif%}
                <!---->
            </div>
          {% endif %}
             
        </div>
        <!-- //left side -->
         <!--end relacionados-->
          <div class="container  mt-5 ">
            <div class="row justify-content-center">
            <div class="col-md-10 col-11 single-left card1">
              {% disqus_show_comments %}
            </div>
              
            </div>
          </div>
      </div>
    </div>
 
  <!-- //blog -->
   
 </div>    

<!-- <h1>{{detalle_blog.id}}</h1> -->

{% endblock section %}
{% block script %}
  <script type="text/javascript" src="{% static 'blog/js/detail_blog.js' %}"></script>
{% endblock %}