apps/blog/urls.py
from django.conf.urls import url, include
# para poder importar las imagenes
from .views import (Blog, Detalle_blog, buscador_blog,
					buscador_categoria, AcercaDe, contador_visitas, tags)
# from views import Users
from django.conf import settings

# from django.views.static.
urlpatterns = [
    # url(r'^users', Users.as_view(), name='inicio'),
    # cuidado con esto tiene GRUD de Users
    # url(r'^$', UserVer.as_view(), name='p_inicio'),
    url(r'api/', include(('apps.blog.api.blog.urls', 'api_blog'), namespace='api_blog')),
    url(r'^$', Blog.as_view(),
        name='p_inicio'),
    url(r'^buscador/$', buscador_blog, name='p_buscador_blog'),
    url(r'^contador-visitas-ajax/$', contador_visitas, name='p_contador_visitas'),
    url(r'^acerca/$', AcercaDe.as_view(), name='p_acerca_de'),
    url(r'^tags/(?P<slug>[^/]+)/$', tags, name='p_tag_blog'),
    url(r'^buscador/categorias/(?P<slug>[^/]+)/$',
        buscador_categoria, name='p_buscador_categoria'),
    url(r'^(?P<slug>[^/]+)/$', Detalle_blog.as_view(), name='p_detalle_blog'),
    
]

apps/users/urls.py
from django.conf.urls import url
# para poder importar las imagenes
from django.views.static import serve
from .views import *
# from views import Users
from django.conf import settings

# from django.views.static.
urlpatterns = [
    # url(r'^usuarios', Users.as_view(), name='inicio'),
    # cuidado con esto tiene GRUD de Users
    # url(r'^$', UserVer.as_view(), name='p_inicio'),
    url(r'^nuevo/$', User_crear.as_view(),
        name='pu_nuevo'),
    url(r'^editar/(?P<pk>\d+)$',
        UserEditar.as_view(), name='p_editar'),
    url(r'^eliminar/(?P<pk>\d+)$',
        UserEliminar.as_view(), name='p_eliminar'),
    url(r'^cambio_contrasena$', change_password,
        name='change_password'),
    url(r'^contrasena$', cambio_contrasena,
        name='p_cambio_contrasena'),
    url(r'^(?P<usuario>[^/]+)$', Ver_perfil.as_view(),
        name='p_ver_perfil'),
    url(r'^(?P<usuario>[^/]+)/editar$', Editar_perfil.as_view(),
        name='p_editar_perfil'),
    url(r'^(?P<usuario>[^/]+)/cuenta$', Cuenta_usuario.as_view(),
        name='p_cuenta'),
    url(r'^cambiar_cuenta_usuario/$', Cambiar_cuenta_usuario.as_view(),
        name='p_cambiar_cuenta_usuario'),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

yachaycode/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.views import (change_password, 
                                        registro_usuario_modals, 
                                        Completar_registro_perfil,
                                        Registrarse, Index_principal,
                                        LogOut, userlogin,
                                        activate)
from apps.users import views as core_views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', Index_principal.as_view(), name="index_principal"),
    path(r'oauth/', include('social_django.urls', namespace='social')),
    path(r'usuarios/', include(('apps.users.urls', 'app_users'), 
        namespace='app_users')),
    path(r'blog/', include(('apps.blog.urls', 'app_blog'), 
        namespace='app_blog')),
    path(r'settings/', core_views.settings, name='settings'),
    path(r'settings/password/', core_views.password, name='password'),
    path(r'iniciar/', userlogin, name="iniciar_sesion"),
    path(r'salir/', LogOut, name='cerrar_sesion'),
        # para recuperacion de contraseña
    path('', include('django.contrib.auth.urls')),
    path(r'registrarse/', Registrarse.as_view(), 
        name="registrarse_usuario"),
    path('martor/', include('martor.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

apps/users/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from requests.api import request

from .models import User, UserProfile
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, TemplateView
from django.urls import reverse_lazy
from .forms import *
from braces.views import LoginRequiredMixin, PermissionRequiredMixin
# import md5
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from apps.blog.models import Blog
# importacio para APIS
from yachaycode import settings
# para validacion de contraseñas
# from django.core.exceptions import ValidationError
# from django.utils.translation import gettext as _
# para cambio de contraseñas
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# para autenticacion con redes sociales
from social_django.models import UserSocialAuth
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, UserCreationForm
# settings y password para controlar autenticacion con redes sociales
# envio de correo cuando apertura una cuenta
from django.conf import settings 
from django.core.mail import send_mail
# para autenticacion persozalizdo
from .functions import UsernameOrEmailBackend

from django.urls import reverse

# para tokens, por ejemplo para confirmacion de email
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site

@login_required
def settings(request):
    user = request.user

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None
    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() >
                      1 or user.has_usable_password())

    return render(request, 'usuarios/settings.html', {
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(
                request, 'Su contraseña fue actualizada con éxito!')
            return redirect('password')
        else:
            messages.error(
                request, 'Por favor corrija el error a continuación.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'usuarios/password.html', {'form': form})


class Index_principal(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(Index_principal,
                        self).get_context_data(**kwargs)
        # context['inscripcion_usuario'] = UserForm()
        blogs = Blog.objects.filter(
        status=True).order_by('-created_at')[:3]
        list_blogs = []
        for blog in blogs:
            dict_blog = {}
            dict_blog['title'] = blog.title
            dict_blog['slug'] = blog.slug
            dict_blog['summary'] = blog.summary[0:250] + '...' if len(blog.summary)>250 else blog.summary
            dict_blog['content'] = blog.content
            dict_blog['categories'] = blog.categories
            dict_blog['cover_image'] = blog.cover_image
            dict_blog['created_at'] = blog.created_at
            dict_blog['author'] = blog.author
            dict_blog['number_views'] = blog.number_views
            dict_blog['keywords'] = blog.keywords
            dict_blog['status'] = blog.status
            dict_blog['is_main_article'] = blog.is_main_article
            dict_blog['related_posts'] = blog.related_posts
            list_blogs.append(dict_blog)
        context['blogs'] = list_blogs
        # pasamos un conjunto de numeros en un rango
        return context


def userlogin(request):
    next = request.GET.get('next', '/')
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        # user = UsernameOrEmailBackend()
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(next)
            else:
                return HttpResponse("usuario inactivo, por favor confirme su cuenta o contáctenos al wsp : 983679449.")
        else:
            messages.error(
            request, 'Correo o contraseña no son correctos..!', extra_tags='danger')
            # return HttpResponseRedirect('/iniciar/')
            return render(request, "login.html", {'redirect_to': next})
    return render(request, "login.html", {'redirect_to': next})


def LogOut(request):
    logout(request)
    return HttpResponseRedirect('/')


class UserEditar(LoginRequiredMixin, UpdateView):

    template_name = 'usuarios/editar_usuario.html'
    success_url = reverse_lazy('app_users:p_inicio')
    model = User
    form_class = UserForm

    def form_valid(self, form):
        if self.request.POST['password'] != '':
            form.instance.set_password(self.request.POST['password'])
        else:
            pass
        # antes capturamos a que grupo pertenecia este usuario, para luego
        # actualizarlo
        pk_user = form.instance.pk
        usuario = get_object_or_404(User, pk=pk_user)
        name_grupo = None
        for g_name in usuario.groups.all():
            name_grupo = g_name.name
        # forzamos el guardado de datos para poder asignar al grupo
        self.object = form.save()
        # y lo guardamos de nuevo al grupo que pertenecia antes, caso contrario
        # el grupo que ha status agregado se liimpiaria
        p_grupo = get_object_or_404(Group, name=name_grupo)
        form.instance.groups.add(p_grupo)
        # agregamos al grupo establecido por el REGISTRADOR
        # redireccionamos al final, OJO: no estamos usando SUPER
        return HttpResponseRedirect(self.get_success_url())


class UserEliminar(LoginRequiredMixin, DeleteView):

    template_name = 'usuarios/eliminar_usuario.html'
    model = User
    success_url = reverse_lazy('app_users:p_inicio')
    context_object_name = 'usuarios'

# Pueden registrar solo los admin


class User_crear(LoginRequiredMixin, CreateView):
    form_class = UserForm
    template_name = 'usuarios/crear_usuario.html'
    success_url = reverse_lazy('app_users:p_inicio')
    user_register = UserForm

    def form_valid(self, form):
        form.instance.set_password(self.request.POST['password'])
        # forzamos el guardado de datos para poder asignar al grupo
        self.object = form.save()
        grupo = get_object_or_404(Group, pk=self.request.POST['tipo_usuario'])
        # agregamos al grupo establecido por el REGISTRADOR
        form.instance.groups.add(grupo)
        # redireccionamos al final, OJO: no estamos usando SUPER
        # generamos su perfil de User
        UserProfile.objects.create(usuario=self.object)
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, *args, **kwargs):
        context_data = super(
            User_crear, self).get_context_data(*args, **kwargs)
        # mostramos todos los grupos a la pertenecera un USUARIO
        grupos = Group.objects.all()
        context_data['grupos'] = grupos
        return context_data


def registro_usuario_modals(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.instance.set_password(request.POST['password'])
            insert = form.save()
            # NOTA: cuidado si cambian de name al grupo habrá error
            grupo = Group.objects.get_or_create(name='Reader')
            insert.groups.add(grupo)
            UserProfile.objects.create(usuario=insert)
            # cuando termine de registrarse, automaticamente
            # iniciamos su sesion de User
            user = authenticate(email=request.POST[
                                'email'], password=request.POST['password'])
            asunto = "Apertura de cuenta | YachayCode"
            mensaje = ('Bienvenido, se ha registrado en yachaycode.\n '
                    'Correo :' + user.email + '\n'
                    'usuario : ' + user.username + '\n'
                    'http://yachaycode.com')
            send_mail(asunto, mensaje, EMAIL_HOST_USER, [user.email])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    perfil = UserProfileForm()
                    return render(request, 'complete_register_user.html',
                                  {'datos_perfil': perfil, 'username': insert.pk})
                else:
                    return HttpResponse("usuario inactivo.")
            else:
                return HttpResponseRedirect('iniciar/')

        else:
            usuario_form = UserForm(form)
            messages.error(
                request, 'Por favor corrija los datos..!', extra_tags='danger')
            return render(request, 'registrarse.html', {'form': usuario_form})
    else:

apps/users/templates/usuarios/base_usuarios.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static from staticfiles %}
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}Yachaycode | Login{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
        <link href="{% static "css/sticky-footer.css" %}" rel="stylesheet">
        <link href="{% static "css/login.css" %}" rel="stylesheet">
        
    </head>
    <body>
        {% block section %}{% endblock %}

    </body>
    {% include "footer.html" %}
</html>

apps/users/templates/usuarios/cambio_contrasena.html
{% extends "base.html" %}
{% block title %}Yachaycode | create username{% endblock title %}
{% block section %}
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

apps/users/templates/usuarios/crear_usuario.html
{% extends "base.html" %}

{% block title %}Yachaycode | Crear usuario{% endblock title %}
{% block section %}
         
        <div class="container-fluid">
           <div class="row">
             <main class="col-sm-12 ml-sm-auto col-md-12 pt-3" role="main">
             <h3>Formulario de registro de User</h3>
			    <section class="content">
			    <div class="col-md-12 table-responsive" >

			    	<a href="{% url 'app_users:p_inicio' %}" class="btn btn-success">
			    	    <span class="glyphicon glyphicon-chevron-left"></span> Atrás
			    	</a>
			    	<form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}

			    	{% if form.errors %}
			    	    <div class="alert alert-danger" role="alert">
			    	        {{ form.errors }}
			    	    </div>
			    	{% endif %}
			    	
			    	<fieldset class="form-group scheduler-border col-md-5">
			    	 		<legend class="scheduler-border">Datos de inicio sesión</legend>

			   	      <div class="form-row">
			   		        <div class="form-group col-xs-6">
			   		        <label >{{form.username.label_tag}} (*)</label>
			   		        {{form.username}}
			   		        </div>
			   	      </div>
			   	      <div class="form-row">
			   	      	<div class="form-group col-xs-2">
			   		          <label>Contraseña (*)</label>
			   		          <input type="password" name="password" class="form-control" required="">
			   		    </div>
			   		    <div class="form-group col-xs-2">
			   		          <label>Repita Contraseña (*)</label>
			   		          <input type="password" name="repassword" class="form-control" required="">
			   		    </div>
			   	      </div>
			   	      <div class="form-row">
			   	      	<div class="form-group col-xs-6">
			   		          <label>Correo (*)</label>
			   		          <input type="email" name="email" class="form-control" required="">
			   		    </div>
			   	      </div>
			   	    </fieldset>
					<fieldset class="form-group scheduler-border col-md-5">
					 		<legend class="scheduler-border">Permisos</legend>
			    	  <div class="form-row">
			    	  	<div class="form-group col-xs-4">
			    	  	  <label>{{ form.tienda.label_tag }}(*)</label>
			    	  	  {{ form.tienda }}
			    	  	</div>
			    	  	<div class="form-group col-xs-4">
			    	  	  <label>Tipo de User(*)</label>
			    	  	  <select name="tipo_usuario" required="" class="form-control">
			    	  	  	<option value="">--------</option>
			    	  	  {% for grupo in grupos %}
			    	  	  	<option value=" {{grupo.pk}} ">{{grupo.name}}</option>	    	  	  	
			    	  	  {% endfor %}
			    	  	  </select>
			    	  	</div>
			    	  </div>
			    	  <br>
			    	  <div class="form-row">
			    	  	<div class="form-group col-xs-3">
			    	  		<label >{{form.is_active.label_tag}} </label>
			    	  		{{form.is_active}}
			    	  	</div>
			    	  	<div class="form-group col-xs-3">
			    	  		<label >(Puede acceder a la parte de ADMIN) </label>
			    	  		{{form.is_staff}}
			    	  	</div>
			    	  	<div class="form-group col-xs-3">
			    	  		<label >{{form.is_superuser.label_tag}} </label>
			    	  		{{form.is_superuser}}
			    	  	</div>

			    	  </div>
					</fieldset>

					<div class="form-row">
			    	  <div class="form-group col-xs-10">
			    	      <button type="submit" class="btn btn-primary">Guardar User</button>
			    	  </div>
			    	</div>
			    	  </form>
			 
				</div>		
			    </section>
             </main>
           </div>
        </div>

{% endblock %}

apps/users/templates/usuarios/editar_usuario.html
{% extends "base.html" %}

{% block title %}Yachaycode | edit user {% endblock title %}
{% block section %}   
        <div class="container-fluid">
           <div class="row">
             <main class="col-sm-12 ml-sm-auto col-md-12 pt-3" role="main">

	       	    <section class="content">
	       	      	<div class="page-header">
	       	      	    <h4>
	       	      	        <a href="{% url 'app_users:p_inicio' %}" class="btn btn-success">
	       	      	            <span class="glyphicon glyphicon-chevron-left"></span> Regresar
	       	      	        </a>
	       	      	        <strong>Editando a: {{ usuario.username }} </strong>
	       	      	    </h4>
	       	      	</div><!-- page-header -->
      		    <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}

      		    	{% if form.errors %}
      		    	    <div class="alert alert-danger" role="alert">
      		    	        {{ form.errors }}
      		    	    </div>
      		    	{% endif %}
      		    	
      		    	<fieldset class="form-group scheduler-border col-md-8">
      		    	 		<legend class="scheduler-border">Datos de inicio sesión</legend>

      		   	      <div class="form-row">
      		   		        <div class="form-group col-xs-3">
      		   		        <label >{{form.username.label_tag}} (*)</label>
      		   		        {{form.username}}
      		   		        </div>
      		   		        <div class="form-group col-xs-3">
      		   		          <label>{{ form.password.label_tag }}(Ingrese uno NUEVO, o dejarlo en blanco)</label>
      		   		          <input type="password" name="password" class="form-control" required="">
      		   		        </div>
      		   	      </div>
      		   	    </fieldset>
      				<fieldset class="form-group scheduler-border col-md-8">
      				 		<legend class="scheduler-border">Permisos</legend>
      		    	  <div class="form-row">
      		    	  	<div class="form-group col-xs-4">
      		    	  	  <label>{{ form.tienda.label_tag }}(*)</label>
      		    	  	  {{ form.tienda }}
      		    	  	</div>
      		    	  	<div class="form-group col-xs-4">
      		    	  	  <label>Tipo de User(*)</label>
      		    	  	  <select name="tipo_usuario" required="" class="form-control">
      		    	  	  	<option value="">--------</option>
      		    	  	  {% for grupo in grupos %}
      		    	  	  	<option value=" {{grupo.pk}} ">{{grupo.name}}</option>	    	  	  	
      		    	  	  {% endfor %}
      		    	  	  </select>
      		    	  	</div>
      		    	  </div>
      		    	  <br>
      		    	  <div class="form-row">
      		    	  	<div class="form-group col-xs-3">
      		    	  		<label >{{form.is_active.label_tag}} </label>
      		    	  		{{form.is_active}}
      		    	  	</div>
      		    	  	<div class="form-group col-xs-3">
      		    	  		<label >(Puede acceder a la parte de ADMIN) </label>
      		    	  		{{form.is_staff}}
      		    	  	</div>
      		    	  	<div class="form-group col-xs-3">
      		    	  		<label >{{form.is_superuser.label_tag}} </label>
      		    	  		{{form.is_superuser}}
      		    	  	</div>

      		    	  </div>
      				</fieldset>

      				<div class="form-row">
      		    	  <div class="form-group col-xs-10">
      		    	      <button type="submit" class="btn btn-primary">Actualizar User</button>
      		    	  </div>
      		    	</div>
      		    </form>
	       	    </section>
             </main>
           </div>
         </div>

{% endblock %}

apps/users/templates/usuarios/eliminar_usuario.html
{% extends "base.html" %}

{% block title %}Yachaycode |Eliminar usuario {% endblock title %}
{% block section %}
         
        <div class="container-fluid">
           <div class="row">
             <main class="col-sm-12 ml-sm-auto col-md-12 pt-3" role="main">
             <section class="content-header">
               <h1>
                 <small>Eliminación de User</small>
               </h1>
               <ol class="breadcrumb">
                 <li><a href="{% url 'app_users:p_inicio' %}"><i class="fa fa-dashboard"></i> Inicio</a></li>
                 <li class="active">Elminar User</li>
               </ol>
             </section>

             <!-- Main content -->
             <section class="content">
               <form role="form" action="{% url 'app_users:p_eliminar' users.id %}" method="POST">{% csrf_token %}
                     <p class="">¿Desea eliminar al User <b>"{{ users.username }}"</b>?</p>
                     <input type="submit" value="Sí" class="btn btn-danger"> 
                     <a href="{% url 'app_users:p_inicio' %}" class="btn btn-default">No</a>
                 </form>
             </section>
             </main>
           </div>
         </div>

{% endblock %}

apps/users/templates/usuarios/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Yachaycode | Users{% endblock title %}

{% block section %}
	<div class="container-fluid">
	   <div class="row">
	     <main class="col-sm-12 ml-sm-auto col-md-12 pt-3" role="main">
	           <section class="content">
	           	<div class="box-header">
	       		    <a class="btn btn-primary pull-right" href=" {% url 'app_users:pu_nuevo' %} ">
	       		        <span class="glyphicon glyphicon-plus"></span>Agregar User
	       		    </a>
	       		    <h3 class="box-title">Listado de todos los Users</h3>
	       		    <p> <b> NOTA: Si desea relizar Cambio de permisos a un User realiza en ADMIN, </b></p>
	       		 </div>
	       	      	<!-- TABLA DINAMICO -->
	       	      	<div class="col-md-12 table-responsive">
	       		    <table id="table1" class="table table-striped table-bordered">
	       		        <thead>
	       		            <tr>
	       		                <th>User del Sistema</th>
	       		                <th>Fecha registro</th>
	       		                <th>Estado</th>
	       		                <th>Correo</th>
	       		                <th>tipo(s) usuario</th>
	       		                <th>Acciones</th>
	       		            </tr>
	       		        </thead>
	       		        <tbody>
	       		        {% for user in users %}
	       		            <tr>
	       		                <td>{{ user.username }}</td>
	       		                <td>{{ user.date_joined }}</td>
	       		                <td>
	       		                	{% if user.is_active  %}
	       								<h5><span class="btn btn-success">Activo</span></h5>
	       								{% else %}
	       								<h5><span class="btn btn-danger">Inactivo</span></h5>
	       							{% endif %}
	       		                </td>
	       		                <td>{{ user.correo }}</td>
	       		                <td>
	       		                	{% for grupos in user.groups.all  %}
	       		                		{{grupos.name}}, 
	       		                	{% endfor %}
	       		                </td>
	       		                <td class="text-right">
	       		                    <a href=" {% url 'app_users:p_editar' user.id %} " class="btn btn-warning btn-xs"><span class="fa fa-pencil"></span></a>
	       		                    <a href=" {% url 'app_users:p_eliminar' user.id %} " class="btn btn-danger btn-xs"><span class="fa fa-trash"></span></a>
	       		                </td>
	       		            </tr>
	       		        {% endfor %}
	       		        </tbody>
	       		    </table>
	       		    </div>
	       				
	           </section>
	     </main>
	   </div>
	 </div>	
{% endblock section %}

apps/users/templates/usuarios/password.html
{% extends "base.html" %}
{% load static %}
{% block title %}Yachaycode | Cambio contraseña{% endblock title %}

{% block section %}
  <div class="container-fluid">
     <div class="row">
       <main class="col-sm-12 ml-sm-auto col-md-12 pt-3" role="main">
             <section class="content">
             	<h4>Cambiar contraseña</h4>
             	{% if not user.has_usable_password %}
             	  <p style="color: red">Aún no has definido una contraseña.</p>
             	{% endif %}
             	<form method="post">
             	  {% csrf_token %}
             	  {{ form.as_p }}
             	  <button type="submit">Guargar cambios</button>
             	</form>
             </section>
       </main>
     </div>
   </div> 
{% endblock section %}

apps/users/templates/usuarios/settings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Yachaycode | Configuracion{% endblock title %}

{% block section %}
  <div class="container-fluid">
     <div class="row">
       <main class="col-sm-6 ml-sm-auto col-md-4 pt-3" role="main">
             <section class="content">
              <h4> <b>Redes Sociales</b> </h4>

              <h5>Twitter</h5>
              {% if twitter_login %}
                <p>Connected as <a href="https://twitter.com/{{ twitter_login.extra_data.access_token.screen_name }}/" target="_blank">@{{ twitter_login.extra_data.access_token.screen_name }}</a></p>
                {% if can_disconnect %}
                  <form method="post" action="{% url 'social:disconnect' 'twitter' %}">
                    {% csrf_token %}
                    <button type="submit">Desconectarse de Twitter</button>
                  </form>
                {% else %}
                  <button type="button" disabled>Desconectarse de Twitter</button>
                  <p style="color: red">Debes <a href="{% url 'password' %}">definir una contraseña</a> para su cuenta antes de desconectarse de Twitter.</p>
                {% endif %}
              {% else %}
                <a href="{% url 'social:begin' 'twitter' %}">Conéctate a Twitter</a>
              {% endif %}

              <h5>Facebook</h5>
              {% if facebook_login %}
                <p>Conectado como <a href="https://facebook.com/{{ facebook_login.extra_data.id }}/" target="_blank">{{ facebook_login.extra_data.id }}</a></p>
                {% if can_disconnect %}
                  <form method="post" action="{% url 'social:disconnect' 'facebook' %}">
                    {% csrf_token %}
                    <button type="submit">Desconectarse de Facebook</button>
                  </form>
                {% else %}
                  <button type="button" disabled>Desconectarse de Facebook</button>
                  <p style="color: red">Debes <a href="{% url 'password' %}">definir una contraseña</a> para su cuenta antes de desconectarse de Facebook.</p>
                {% endif %}
              {% else %}
                <a href="{% url 'social:begin' 'facebook' %}">Conéctate a Facebook</a>
              {% endif %}
             
             </section>
       </main>
     </div>
   </div> 
{% endblock section %}