apps/users/urls.py
from django.conf.urls import url
# para poder importar las imagenes
from django.views.static import serve
from .views import *
# from views import Users
from django.conf import settings

# from django.views.static.
urlpatterns = [
    # url(r'^usuarios', Users.as_view(), name='inicio'),
    # cuidado con esto tiene GRUD de Users
    # url(r'^$', UserVer.as_view(), name='p_inicio'),
    url(r'^nuevo/$', User_crear.as_view(),
        name='pu_nuevo'),
    url(r'^editar/(?P<pk>\d+)$',
        UserEditar.as_view(), name='p_editar'),
    url(r'^eliminar/(?P<pk>\d+)$',
        UserEliminar.as_view(), name='p_eliminar'),
    url(r'^cambio_contrasena$', change_password,
        name='change_password'),
    url(r'^contrasena$', cambio_contrasena,
        name='p_cambio_contrasena'),
    url(r'^(?P<usuario>[^/]+)$', Ver_perfil.as_view(),
        name='p_ver_perfil'),
    url(r'^(?P<usuario>[^/]+)/editar$', Editar_perfil.as_view(),
        name='p_editar_perfil'),
    url(r'^(?P<usuario>[^/]+)/cuenta$', Cuenta_usuario.as_view(),
        name='p_cuenta'),
    url(r'^cambiar_cuenta_usuario/$', Cambiar_cuenta_usuario.as_view(),
        name='p_cambiar_cuenta_usuario'),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

yachaycode/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.views import (change_password, 
                                        registro_usuario_modals, 
                                        Completar_registro_perfil,
                                        Registrarse, Index_principal,
                                        LogOut, userlogin,
                                        activate)
from apps.users import views as core_views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', Index_principal.as_view(), name="index_principal"),
    path(r'oauth/', include('social_django.urls', namespace='social')),
    path(r'usuarios/', include(('apps.users.urls', 'app_users'), 
        namespace='app_users')),
    path(r'blog/', include(('apps.blog.urls', 'app_blog'), 
        namespace='app_blog')),
    path(r'settings/', core_views.settings, name='settings'),
    path(r'settings/password/', core_views.password, name='password'),
    path(r'iniciar/', userlogin, name="iniciar_sesion"),
    path(r'salir/', LogOut, name='cerrar_sesion'),
        # para recuperacion de contraseña
    path('', include('django.contrib.auth.urls')),
    path(r'registrarse/', Registrarse.as_view(), 
        name="registrarse_usuario"),
    path('martor/', include('martor.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

apps/users/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from requests.api import request

from .models import User, UserProfile
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, TemplateView
from django.urls import reverse_lazy
from .forms import *
from braces.views import LoginRequiredMixin, PermissionRequiredMixin
# import md5
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from apps.blog.models import Blog
# importacio para APIS
from yachaycode import settings
# para validacion de contraseñas
# from django.core.exceptions import ValidationError
# from django.utils.translation import gettext as _
# para cambio de contraseñas
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# para autenticacion con redes sociales
from social_django.models import UserSocialAuth
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, UserCreationForm
# settings y password para controlar autenticacion con redes sociales
# envio de correo cuando apertura una cuenta
from django.conf import settings 
from django.core.mail import send_mail
# para autenticacion persozalizdo
from .functions import UsernameOrEmailBackend

from django.urls import reverse

# para tokens, por ejemplo para confirmacion de email
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site

@login_required
def settings(request):
    user = request.user

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None
    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() >
                      1 or user.has_usable_password())

    return render(request, 'usuarios/settings.html', {
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(
                request, 'Su contraseña fue actualizada con éxito!')
            return redirect('password')
        else:
            messages.error(
                request, 'Por favor corrija el error a continuación.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'usuarios/password.html', {'form': form})


class Index_principal(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(Index_principal,
                        self).get_context_data(**kwargs)
        # context['inscripcion_usuario'] = UserForm()
        blogs = Blog.objects.filter(
        status=True).order_by('-created_at')[:3]
        list_blogs = []
        for blog in blogs:
            dict_blog = {}
            dict_blog['title'] = blog.title
            dict_blog['slug'] = blog.slug
            dict_blog['summary'] = blog.summary[0:250] + '...' if len(blog.summary)>250 else blog.summary
            dict_blog['content'] = blog.content
            dict_blog['categories'] = blog.categories
            dict_blog['cover_image'] = blog.cover_image
            dict_blog['created_at'] = blog.created_at
            dict_blog['author'] = blog.author
            dict_blog['number_views'] = blog.number_views
            dict_blog['keywords'] = blog.keywords
            dict_blog['status'] = blog.status
            dict_blog['is_main_article'] = blog.is_main_article
            dict_blog['related_posts'] = blog.related_posts
            list_blogs.append(dict_blog)
        context['blogs'] = list_blogs
        # pasamos un conjunto de numeros en un rango
        return context


def userlogin(request):
    next = request.GET.get('next', '/')
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        # user = UsernameOrEmailBackend()
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(next)
            else:
                return HttpResponse("usuario inactivo, por favor confirme su cuenta o contáctenos al wsp : 983679449.")
        else:
            messages.error(
            request, 'Correo o contraseña no son correctos..!', extra_tags='danger')
            # return HttpResponseRedirect('/iniciar/')
            return render(request, "login.html", {'redirect_to': next})
    return render(request, "login.html", {'redirect_to': next})


def LogOut(request):
    logout(request)
    return HttpResponseRedirect('/')


class UserEditar(LoginRequiredMixin, UpdateView):

    template_name = 'usuarios/editar_usuario.html'
    success_url = reverse_lazy('app_users:p_inicio')
    model = User
    form_class = UserForm

    def form_valid(self, form):
        if self.request.POST['password'] != '':
            form.instance.set_password(self.request.POST['password'])
        else:
            pass
        # antes capturamos a que grupo pertenecia este usuario, para luego
        # actualizarlo
        pk_user = form.instance.pk
        usuario = get_object_or_404(User, pk=pk_user)
        name_grupo = None
        for g_name in usuario.groups.all():
            name_grupo = g_name.name
        # forzamos el guardado de datos para poder asignar al grupo
        self.object = form.save()
        # y lo guardamos de nuevo al grupo que pertenecia antes, caso contrario
        # el grupo que ha status agregado se liimpiaria
        p_grupo = get_object_or_404(Group, name=name_grupo)
        form.instance.groups.add(p_grupo)
        # agregamos al grupo establecido por el REGISTRADOR
        # redireccionamos al final, OJO: no estamos usando SUPER
        return HttpResponseRedirect(self.get_success_url())


class UserEliminar(LoginRequiredMixin, DeleteView):

    template_name = 'usuarios/eliminar_usuario.html'
    model = User
    success_url = reverse_lazy('app_users:p_inicio')
    context_object_name = 'usuarios'

# Pueden registrar solo los admin


class User_crear(LoginRequiredMixin, CreateView):
    form_class = UserForm
    template_name = 'usuarios/crear_usuario.html'
    success_url = reverse_lazy('app_users:p_inicio')
    user_register = UserForm

    def form_valid(self, form):
        form.instance.set_password(self.request.POST['password'])
        # forzamos el guardado de datos para poder asignar al grupo
        self.object = form.save()
        grupo = get_object_or_404(Group, pk=self.request.POST['tipo_usuario'])
        # agregamos al grupo establecido por el REGISTRADOR
        form.instance.groups.add(grupo)
        # redireccionamos al final, OJO: no estamos usando SUPER
        # generamos su perfil de User
        UserProfile.objects.create(usuario=self.object)
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, *args, **kwargs):
        context_data = super(
            User_crear, self).get_context_data(*args, **kwargs)
        # mostramos todos los grupos a la pertenecera un USUARIO
        grupos = Group.objects.all()
        context_data['grupos'] = grupos
        return context_data


def registro_usuario_modals(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.instance.set_password(request.POST['password'])
            insert = form.save()
            # NOTA: cuidado si cambian de name al grupo habrá error
            grupo = Group.objects.get_or_create(name='Reader')
            insert.groups.add(grupo)
            UserProfile.objects.create(usuario=insert)
            # cuando termine de registrarse, automaticamente
            # iniciamos su sesion de User
            user = authenticate(email=request.POST[
                                'email'], password=request.POST['password'])
            asunto = "Apertura de cuenta | YachayCode"
            mensaje = ('Bienvenido, se ha registrado en yachaycode.\n '
                    'Correo :' + user.email + '\n'
                    'usuario : ' + user.username + '\n'
                    'http://yachaycode.com')
            send_mail(asunto, mensaje, EMAIL_HOST_USER, [user.email])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    perfil = UserProfileForm()
                    return render(request, 'complete_register_user.html',
                                  {'datos_perfil': perfil, 'username': insert.pk})
                else:
                    return HttpResponse("usuario inactivo.")
            else:
                return HttpResponseRedirect('iniciar/')

        else:
            usuario_form = UserForm(form)
            messages.error(
                request, 'Por favor corrija los datos..!', extra_tags='danger')
            return render(request, 'registrarse.html', {'form': usuario_form})
    else:

apps/users/templates/usuarios/perfil/cuenta.html
{% extends "base.html" %}
{% load static %}
{% block title %}Yachaycode | Cuenta {% endblock title %}

{% block section %}

      <!--star cuenta-->
  <div class="container-fluid">
    <div class="row ">
        <div class="col-md-4 fond_perfi">
            <div class="col-md-12 sub_menu_div">
               <h6 class="card-title sub_menu_perf"><i class="fa fa-cog sub_menu_perf" aria-hidden="true"></i><strong> CONFIGURACIÓN</strong></h6>      
            </div>
            <div class="col-md-12 sub_menu_div">
               <a class="" href="{% url 'app_users:p_editar_perfil' request.user.username %}"><strong><span class="sub_menu_perf">Perfil</span></strong></a>
            </div>
            <div class="col-md-12 sub_menu_div">
               <a class="" href="#"><strong><span class="sub_menu_perf">Cuenta</span></strong></a>
            </div>
          
        </div>


        <div class="col-md-8 bord fond_perfi1">
           <div class="container">
              <div class="row my-3 d-flex justify-content-center">
                  <div class="col-md-12">
                      <h4 class="card-title">Cuenta</h4>
                  </div>
                  {% if form.errors %}
                      <div class="alert alert-danger" role="alert">
                          {{ form.errors }}
                      </div>
                  {% endif %}
               
              </div>
               <hr>

             <div class="row esp">
                  <div class="col-md-8">
                   
                        <label for="exampleSelect1">Nombre de usuario y correo</label>
                        <p>
                          Puedes cambiar tus datos. Cambiar tu usuario va afectar tu inicio de sesión y la URL de tu perfil.
                        </p>
                  
                  </div>
                
             </div>
              <form action=" {% url 'app_users:p_cambiar_cuenta_usuario' %} " method="POST">{% csrf_token %}
                <div class="row esp">
                
                  <div class="col-md-6">
                      <div class="md-form">
                        <input type="text" id="form52" class="form-control" value="{{request.user.username}}" name="username">
                        <label for="form52" class="">Nombre de usuario</label>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="md-form">
                      <input type="text" id="form51" class="form-control" value=" {{request.user.email}} " name="email">
                      <label for="form51" class="">Nombre de Correo</label>
                    </div>
                  </div>
                </div>
                  <button type="submit" class="btn btn-primary">Actualizar datos</button>
              </form>

            <hr>
             <div class="row my-3 d-flex justify-content-center">
                 <div class="col-md-12">
                     <h4 class="card-title">Contraseña</h4>
                 </div>          
             </div>
            <form action=" {% url 'app_users:p_cambio_contrasena' %}" method="POST">{% csrf_token %}
              {% if form_password.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ form_password.errors }}
                  </div>
              {% endif %}
               <div class="row peq1">
                   <div class="col-md-6">
                        <div class="md-form">
                          {{form_password.old_password}}
                          {{form_password.old_password.label_tag}}
                      </div>
                    </div>
              </div>
              <br>
             <div class="row esp">
                  <div class="col-md-6">
                       <div class="md-form">
                         {{form_password.new_password1}}
                         {{form_password.new_password1.label_tag}}
                     </div>
                   </div>
                  <div class="col-md-6">
                       <div class="md-form">
                         {{form_password.new_password2}}
                         {{form_password.new_password2.label_tag}}
                     </div>
                   </div>
             </div>
             <div class="row ">
                     <button type="submit" class="btn btn-primary">Cambiar contraseña</button>
             </div>
            </form>


          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid contenedor_color">
       <div class="row paddin_perf">
       </div>
    </div>
{%endblock%}

apps/users/templates/usuarios/perfil/editar_perfil.html
{% extends "base.html" %}
{% load static %}
{% block title %}Yachaycode | editar perfil {% endblock title %}

{% block section %}

  <!--star editar perfil-->
  <div class="container-fluid contene_perfil">
        <div class="row">
        <div class="col-md-4 fond_perfi">
            <div class="col-md-12 sub_menu_div">
               <h6 class="card-title sub_menu_perf"><i class="fa fa-cog sub_menu_perf" aria-hidden="true"></i><strong> CONFIGURACIÓN</strong></h6>      
            </div>
            <div class="col-md-12 sub_menu_div">
               <a class="" href="#"><strong><span class="sub_menu_perf">Perfil</span></strong></a>
            </div>
            <div class="col-md-12 sub_menu_div">
               <a class="" href=" {% url 'app_users:p_cuenta' request.user.username %} "><strong><span class="sub_menu_perf">Cuenta</span></strong></a>
            </div>
            <div class="col-md-12 sub_menu_div">
               <p>PERFILES SOCIALES</p>
            </div>
        </div>
        <div class="col-md-8 bord fond_perfi1">
          <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.errors }}
                </div>
            {% endif %}
           <div class="container">
              <div class="row my-3 d-flex justify-content-center">
                  <div class="col-md-6">
                      <h4 class="card-title">Perfil</h4>
                  </div>
                  <div class="col-md-6">
                     <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
              </div>
               <hr>
              <div class="row ">
                 <div class="col-md-6 ">
                    <img src="{{request.user.userprofile.photo.url}}" class="rounded-circle z-depth-1-half" width="100" height="120">
                 </div>
                 <div class="col-md-6 ">
                    <label for="">Actualizar foto:</label>
                    {{form.photo}}
                 </div>
             </div>
              <hr>
             <div class="row">
               <div class="col-md-6">
                  <h4 class="card-title">Informacion personal</h4>
               </div>
             </div>

             <div class="row esp">
                  <div class="col-md-6">
                      <div class="md-form">
                        {{form.first_name}}
                        {{form.first_name.label_tag}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="md-form">
                        {{form.last_name}}
                        {{form.last_name.label_tag}}
                    </div>
                  </div>
             </div>

            <div class="row esp">
            <div class="col-md-6">
                <div class="md-form hi">
                    {{form.cellphone}}
                    {{form.cellphone.label_tag}}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    {{form.country.label_tag}}
                   {{form.country}}
                </div>
            </div>

           </div>

           <div class="row esp">
            <div class="col-md-6">
                <div class="row">
                    <div class="col">
                       <div class="form-group">
                          {{form.birth_date.label_tag}}
                          {{form.birth_date}}
                          <p class="help-block">Formato de fecha. DIA/MES/AÑO </p>
                      </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                     {{form.sexo.label_tag}}
                     {{form.sexo}}
                </div>
            </div>
           </div>

            <div class="row esp">
                  <div class="col-md-6">
                      <div class="md-form">
                        {{form.city}}
                        {{form.city.label_tag}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="md-form">
                        {{form.occupation}}
                        {{form.occupation.label_tag}}
                    </div>
                  </div>
             </div>

              <div class="row esp">
                  <div class="col-md-6">
                      <div class="md-form">
                        {{form.profession}}
                        {{form.profession.label_tag}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="md-form">
                        {{form.website}}
                        {{form.website.label_tag}}
                    </div>
                  </div>
             </div>
              <div class="row esp">
                  <div class="col-md-12">
                      <div class="md-form">
                          {{form.biography}}
                          {{form.biography.label_tag}}
                      </div>
                  </div>
              </div>
                <div class="row">
                    <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
          </div>
        </form>
        </div>
      </div>
  </div>
    <div class="container-fluid contenedor_color">
       <div class="row paddin_perf">
       </div>
    </div>
{%endblock%}