apps/blog/urls.py
from django.conf.urls import url, include
# para poder importar las imagenes
from .views import (Blog, Detalle_blog, buscador_blog,
					buscador_categoria, AcercaDe, contador_visitas, tags)
# from views import Users
from django.conf import settings

# from django.views.static.
urlpatterns = [
    # url(r'^users', Users.as_view(), name='inicio'),
    # cuidado con esto tiene GRUD de Users
    # url(r'^$', UserVer.as_view(), name='p_inicio'),
    url(r'api/', include(('apps.blog.api.blog.urls', 'api_blog'), namespace='api_blog')),
    url(r'^$', Blog.as_view(),
        name='p_inicio'),
    url(r'^buscador/$', buscador_blog, name='p_buscador_blog'),
    url(r'^contador-visitas-ajax/$', contador_visitas, name='p_contador_visitas'),
    url(r'^acerca/$', AcercaDe.as_view(), name='p_acerca_de'),
    url(r'^tags/(?P<slug>[^/]+)/$', tags, name='p_tag_blog'),
    url(r'^buscador/categorias/(?P<slug>[^/]+)/$',
        buscador_categoria, name='p_buscador_categoria'),
    url(r'^(?P<slug>[^/]+)/$', Detalle_blog.as_view(), name='p_detalle_blog'),
    
]

yachaycode/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.views import (change_password, 
                                        registro_usuario_modals, 
                                        Completar_registro_perfil,
                                        Registrarse, Index_principal,
                                        LogOut, userlogin,
                                        activate)
from apps.users import views as core_views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', Index_principal.as_view(), name="index_principal"),
    path(r'oauth/', include('social_django.urls', namespace='social')),
    path(r'usuarios/', include(('apps.users.urls', 'app_users'), 
        namespace='app_users')),
    path(r'blog/', include(('apps.blog.urls', 'app_blog'), 
        namespace='app_blog')),
    path(r'settings/', core_views.settings, name='settings'),
    path(r'settings/password/', core_views.password, name='password'),
    path(r'iniciar/', userlogin, name="iniciar_sesion"),
    path(r'salir/', LogOut, name='cerrar_sesion'),
        # para recuperacion de contraseña
    path('', include('django.contrib.auth.urls')),
    path(r'registrarse/', Registrarse.as_view(), 
        name="registrarse_usuario"),
    path('martor/', include('martor.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>

        {% load static from staticfiles %}
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}YachayCode{% endblock %}</title>
        <!-- <link rel="shortcut icon" type="image/png" href=" {% static "img/favicon/faviconhero.png" %}"/> -->
        <meta name="description" content=" Blog sobre la tecnologia y desarrollo de software">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!--SEO -->
        <meta name="author" content="{% block author %}Yachay Code{% endblock %}"/>
        <meta name="copyright" content="Copyright 2018 by Yachay Code" />
        <meta name="disribution" content="global" />
        <meta name="theme-color" content="#ff1500" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
        <link rel="canonical" href="{% block canonical %}https://yachaycode.com/{% endblock %}">
        <link rel="shortcut icon" type="image/png" href=" {% static 'img/favicon/faviconyachay.png' %}"/>
        <meta name="description" content="{% block description %}Creando tecnología, escriendo y compartiendo experiencias{% endblock %}">
        <meta name="twitter:card" content="summary">
        <meta name="twitter:title" content="{% block twitter_title %}Yachay Code{% endblock %}">
        <meta name="twitter:description" content="{% block twitter_description %}Creando tecnología, escriendo y compartiendo experiencias {% endblock %}">
        <meta name="twitter:image" content="{% block twitter_image %}https://yachaycode.com/static/img/logo_hero.png{% endblock %}" />
        <meta name="twitter:creator" content="{% block twitter_creator %}Yachay Code{% endblock %}">
        <meta property="fb:app_id" content="133591580646053"/>
        <meta property="fb:site_name" content="{% block fb_site_name %}Yachay Code{% endblock %}" />
        <meta property="og:url" content="{% block og_url %}https://yachaycode.com/{% endblock %}">
        <meta property="og:title" content="{% block og_title %}Yachay Code{% endblock %}">
        <meta property="og:description" content="{% block og_description %}Creando tecnología, escriendo y compartiendo experiencias {% endblock %}">
        <meta property="og:image" content="{% block og_image %}https://yachaycode.com/static/img/logo_hero.png{% endblock %}" />
        <meta property="og:site_name" content="{% block og_site_name %}Yachay Code{% endblock %}">

        <meta property="keywords" content="{% block keywords %}{% endblock %}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Bootstrap core CSS -->
        {% block general_imports %}
            <link href=" {% static "css/bootstrap.min.css" %} " rel="stylesheet">
            <!-- Material Design Bootstrap -->
            <link href=" {% static "css/mdb.min.css" %} " rel="stylesheet">
            <!-- Your custom styles (optional) -->
            <link href=" {% static "css/style.css" %} " rel="stylesheet">
            <!-- Icon font -->
            <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
            <!-- Font Awesome -->
            <link rel="stylesheet" href="{% static 'css/fontawsome-582-all.css' %}">
            <!-- Material Desing -->
            <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
            <!-- Some General Icons -->
            <link href="{% static 'css/icone91f.css' %}" rel="stylesheet">
            <!-- General Styles -->
            <link rel="stylesheet" href="{% static 'css/global.css' %}">
            <link rel="stylesheet" href="{% static 'css/global2.css' %}">
        {% endblock %}
        {% block head_imports %}
        {% endblock %}

    </head>
    <body>
        
        {% include 'messages.html' %}
        {% include 'header.html' %}
        {% block section %}{% endblock %}
      <!-- SCRIPTS -->
      <!-- JQuery -->
      <script type="text/javascript" src=" {% static "js/jquery-3.2.1.min.js" %} "></script>
      <!-- Bootstrap tooltips -->
      <script type="text/javascript" src=" {% static "js/popper.min.js" %} "></script>
      <!-- Bootstrap core JavaScript -->
      <script type="text/javascript" src="{% static "js/bootstrap.min.js" %} "></script>
      <!--JavaScript -->
      <script type="text/javascript" src=" {% static "js/script.js" %} "></script>
    {% block script %}
    {% endblock %}

</body>
    {% include "footer.html" %}
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<footer class="page-footer font-small fond_footer pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left ">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h4 class="mb-3 f-mont size25">YachayCode</h4>
        <p class="color-p f-mont-r size15">
          Apasionados por la tecnología, computación y la informática; compartiendo experiencias mediante generación de contenido de valor en este blog.
        </p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h5 class="mb-3 f-mont size18">Sobre nosotros</h5>
        <a href="/blog/acerca/" target="_blank"><i class=" footer_icon"></i><p class="color-p f-mont-r size15">Acerca del blog</p></a>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h5 class="mb-3 f-mont size18">Contactos</h5>
        <p class="color-p f-mont-r size15">    <i class="fa fa-envelope mr-3"></i>yachaycode@gmail.com</p>
        <a href="https://web.whatsapp.com/send?phone=51983679449" target="_blank"><i class="fab fa-whatsapp footer_icon"></i></a>
        <a href="https://t.me/joinchat/8XfneRKrWrQ0ZDMx" target="_blank"><i class="fab fa-telegram footer_icon"></i></a>
        <a href="https://www.facebook.com/Yachaycode-618908005122073/" target="_blank"><i class="fab fa-facebook-f footer_icon"></i></a>
        <a href="https://twitter.com/yachaycode" target="_blank"><i class="fab fa-twitter footer_icon"></i></a>
        <a href="https://github.com/yachaycode" target="_blank"><i class="fab fa-github footer_icon"></i></a>
        <a href="https://www.youtube.com/channel/UChd1mszMRyIKgGnlsSdMiuA?disable_polymer=true" target="_blank"><i class="fab fa-youtube footer_icon "></i></a></p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Footer links -->

    <hr class="w-100">

    <!-- Grid row -->
    <div class="row d-flex justify-content-center">

      <!-- Grid column -->
      <div class="text-center">

        <div class="text-md-center ">
          <p class="f-mont size15 text-center">
            Copyright@YachayCode 2021 - {% now "Y" %}
          </p>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->

templates/header.html
{% load static %}
<!--Navbar-->
  <nav class="menu">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- logo -->
      <div class="pl-4 pr-3 pt-2">
        <!-- logo -->
        <a title="Logo Yachaycode" href="/"><img loading="lazy" class="img-fluid logo-inicio"
            src="/static/img/logo.png" alt="YachayCode" /></a>
      </div>
    </div>
  
    <div class="collapse menu-collapse m-0 p-0" id="menu">
      <ul class="menu-nav idx">
        <li><a href="{% url 'app_blog:p_acerca_de' %}" class="size14 color-grey f-mont">Nosotros</a></li>
        <li><a href="{% url 'app_blog:p_inicio' %} " class="size14 color-grey f-mont">Blog</a></li>
      </ul>
  
      <ul class="nav navbar-right nav-right">

        <li class="pt-1">
        </li>

        <div class="md-form my-0 pr-3">
          <ul class="menu-nav idx">
            <li class="no-border">
              <a class="buton_ingre pl-3 pr-3 hv-acceso" href="{% url 'admin:index' %}" id="login_user">
                <span class="size14 line1 f-mont color-grey">Acceder</span>
                <i class="fas fa-angle-right pl-2 size14 color-grey"></i></a>
            </li>
          </ul>
        </div>

      </ul>
    </div>
  </nav>
<!--/.Navbar-->

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}YachayCode - Inicio {% endblock title %}
{% block author %}YachayCode{% endblock author %}
{% block canonical %}https://yachaycode.com/{% endblock canonical %}
{% block description %}Blog donde un equipo de profesionales apasionados por la tecnología, computación y la informática; comparten experiencias profesionales y personales generando contenido de valor.
{% endblock description %}

{% block twitter_title %}YachayCode{% endblock twitter_title %}

{% block twitter_description %}Blog donde un equipo de profesionales apasionados por la tecnología, computación y la informática; comparten experiencias profesionales y personales generando contenido de valor.{% endblock twitter_description %}

{% block twitter_creator %}YachayCode{% endblock twitter_creator %}

{% block og_url %}https://yachaycode.com{% endblock og_url %}

{% block og_title %}YachayCode{% endblock og_title %}

{% block og_description %}Blog donde un equipo de profesionales apasionados por la tecnología, computación y la informática; comparten experiencias profesionales y personales generando contenido de valor.{% endblock og_description %}

{% block keywords %} Desarrollo de software, startup, innovación, transformación digital, devops, yachay {% endblock keywords %}

{% block section %}

{% block head_imports %}
{% endblock %}

<!--/.start bannner-->
<div class="container-fluid m-0 p-0 bg-color1">
  <div class="contenedor-banner banner pt-general">
  <div class="row">
     <div class="col-md-6 centerv">
       <form class="form-inline" method="GET" action="/blog/buscador">
        <div class="row vert-banner  mg-l">
                <h2 class="title-banner pb-2 f-mont size30"><b>Comunidad YachayCode</b><br></h2>
              <p class="p-banner f-mont size18">Aprendiendo y compartiendo sobre Desarrollo de Software.</p>
              <div class="col-md-9 container-1 pt-3 p-0 m-0">
                    <span class="icon"><i class="fa fa-search"></i></span>
                    <input class="form-control search f-mont size15" type="text" id="q" name="q" placeholder="Buscar..." />
              </div>     
        </div>
        </form>
        {% if blogs %}
            <h2 class="mb-5">{{ blogs.title }}</h2>
            <p>{{ blogs.summary }}</p>
        {%else%}
        <h5> No se encontraron resultados</h5>
        {% endif %}
     </div>
     <div class="col-md-6 img-banner"></div>
  </div>
</div>
</div>
<!--/.end bannner-->

<div class="container mb-lg1">
  <div class="row mt-5 mb-5">
    <div class="col-md-12 text-center">
       <h5 class="color-title f-mont size18" id="myModalLabel"><b>Últimas publicaciones</b></h5>
    </div>
  </div>
   
  <div class="row mb-5">
  {% for blog in blogs %}
    <div class="col-md-4 mb-4">
      <!-- Card -->
        <div class="card">

          <!-- Card image -->
          <div class="view overlay">
            <img class="card-img-top f-mont" src="{{ blog.cover_image.url }}" alt="Card image cap">
            <a href="{% url 'app_blog:p_detalle_blog' blog.slug %}">
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>

          <!-- Card content -->
          <div class="card-body">

            <!-- Title -->
            <a href="{% url 'app_blog:p_detalle_blog' blog.slug %}"><h5 class="card-title f-mont">{{blog.title}}</h5></a>
              <p class="text-avatar size12 m-0 c-gray">{{blog.created_at|date:"d M, Y"}}</p>
            <!-- Text -->
            <p class="size12 c-gray">{{blog.summary}} </p>
            <!-- Button -->
          

          </div>
           <!-- Card footer -->
            <div class="rounded-bottom lighten-3 pt-0">
              <div class="row pd-gblog mb-1">
                  <div class="col-md-8">
                    <div class="row justify-content-center">
                        <div class="col-md-2 ">
                              <div class="avatar-blog ">
                              <img src="{{ blog.author.userprofile.photo.url }}" class="rounded-circle img-fluid">
                              </div>
                        </div>
                          
                        <div class="col-md-10  pd-lblog cy-blog">
                            <p class="text-avatar size12 c-gray">Posteado por 
                              {% if blog.author.userprofile.first_name and blog.author.userprofile.last_name %}
                                <b>{{ blog.author.userprofile.first_name }} {{ blog.author.userprofile.last_name }}</b>
                              {% else %}
                                <b>{{ blog.author.userprofile.username }}</b>
                              {% endif %}
                            </p>
                        </div>
                    </div>
                  </div>
            </div>

          </div>
        </div>
        <!-- Card -->
    </div>
  {% endfor %}


  </div>

  <div class="text-center pt-4 pb-5">
    <a href="{% url 'app_blog:p_inicio' %}" class="title-banner m-5">Leer más<i
        class="fas fa-chevron-right ml-2"></i></a>
  </div>

  </div>

{% endblock %}

templates/login.html
{% extends "base_registro_usuario.html" %}
{% block title %}Inicio de Sesión{% endblock title %}
{% load static %}
{% block section %}

<div class="container">
  {% if not request.user.is_authenticated %}
  <div class="row justify-content-center ">

  	   <form action=".?next={{ redirect_to }}" method="post" class="form-signin">{% csrf_token %}
      {% if form.errors %}
		      <div class="alert alert-danger" role="alert">
		          {{ form.errors }}
		      </div>
		{% endif %}
    <div class="card col-md-12">

        <div class="card-body mx-4">

           
            <div class="text-center">
                <h3 class="dark-grey-text mb-5"><strong>Iniciar sesión</strong></h3>
            </div>

            <!--Body-->
              <div class="row my-3 d-flex justify-content-center">
                     
                <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ redirect_to }}"> <button type="button" class="btn btn-red btn-rounded mr-md-3 z-depth-1a">Continuar con : <i class="fa fa-google  text-center"></i></button></a>
                
                 {# <a href="{% url 'social:begin' 'twitter' %}?next={{ redirect_to }}"><button type="button"class="btn btn-info btn-rounded mr-md-3 z-depth-1a">Continuar con :<i class="fa fa-twitter "></i></button></a> #}
                 <a href="{% url 'social:begin' 'facebook' %}?next={{ redirect_to }}"> <button type="button" class="btn btn-blue btn-rounded mr-md-3 z-depth-1a">Continuar con: <i class="fa fa-facebook blue-text text-center"></i></button> </a>
              </div>

            <div class="md-form">
                <input type="email" id="Form-email1" name="email" class="form-control">
                <label for="Form-email1">Correo electrónico</label>
            </div>

            <div class="md-form pb-3">
                <input type="password" id="Form-pass1" name="password" class="form-control">
                <label for="Form-pass1">Contraseña</label>
                <a href=" {% url 'password_reset' %}" class="blue-text ml-1"><p class="font-small blue-text d-flex justify-content-end">Olvidastes tu Contraseña?</p></a>
            </div>

            <div class="text-center mb-3">
                <button type="submit" class="btn btn-primary btn-block ">Iniciar<i class="fa fa-sign-in ml-1"></i> </button>
            </div>


        </div>

        <!--Footer-->
        <div class="modal-footer mx-5 pt-3 mb-1">
            <p class="font-small grey-text d-flex justify-content-end">No eres miembro? <a href=" {% url 'registrarse_usuario' %} " class="blue-text ml-1"> Registrate</a></p>
        </div>

    </div>
</form>	
  </div>
    {% else %}
    <p>Ya inicio su sesión <a href=" {% url 'cerrar_sesion' %} ">Cerrar</a></p>
    {% endif %}
</div>

{% endblock section %}

templates/messages.html
<div class="form-row justify-content-center">
  <div class="form-group col-md-6">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
        </button>
        {{ message }} 
    </div>
    {%endfor%}

  </div>
</div>